spring:
  config:
    import: jwt.yml
  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
    url: jdbc:postgresql://localhost:5432/commenting
    username: jayce
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: '232728586772-bipelclpbc3amsmgai881ct8m1opt93f.apps.googleusercontent.com'
            clientSecret: 'opUiQoAu2sU5IsvUBXtZHHx4'
            scope: ['email', 'profile']
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            user-name-attribute: sub
  mail:
    host: smtp.gmail.com
    port: 587
    username: jayce8887@gmail.com
    password: szzpnqdfgeozkobk
    properties:
      mail:
        debug: true
        smtp.auth: true
        smtp.timeout: 50000
        smtp.starttls.enable: true
  data:
    redis:
      mail:
        host: localhost
        port: 6379
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/commenting
#    username: jiheon
#    password: "0000"
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  paths-to-match: /**
  swagger-ui:
    path: /swagger
    display-request-duration: true
    groups-order: desc
    operations-sorter: alpha
    disable-swagger-default-url: true
  api-docs:
    groups:
      enabled: true
logging:
  level:
    org.springframework.security: DEBUG